/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uc.seng301.cardbattler.asg4;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void given_a_test_always_passes_when_its_ran_then_it_passes() {
        Assertions.assertTrue(true);
    }
}
